# Generated by Django 6.0.7 on 2026-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_threshold', models.IntegerField(default=25)),
                ('loiter_seconds', models.IntegerField(default=8)),
                ('unknown_seconds', models.IntegerField(default=3)),
                ('unattended_seconds', models.IntegerField(default=5)),
                ('weight_unknown', models.IntegerField(default=40)),
                ('weight_loitering', models.IntegerField(default=25)),
                ('weight_unattended', models.IntegerField(default=30)),
            ],
        ),
    ]
