# Generated by Django 6.0.7 on 2026-08-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_systemsettings_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='event',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
    ]
